package io.github.haroldhues.Tokens;

public enum TokenType {
    Identifier,
    IntegerLiteral,
    Read,
    Write,
    If,
    Else,
    Int,
    Return,
    Void,
    While,
    Add,
    Subtract,
    Multiply,
    Divide,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    Equal,
    NotEqual,
    Assign,
    Semicolon,
    Comma,
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Eof,
}